//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerApiKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerApiKey()
        {
            this.CustomerApiKeyRules = new HashSet<CustomerApiKeyRule>();
        }
    
        public int Id { get; set; }
        public string ApiKey { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> LockedUntil { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public string ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerApiKeyRule> CustomerApiKeyRules { get; set; }
    }
}
